// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLJpEQ1Lw2_ab1b_P7L49vCmNBsX9WqUo',
    appId: '1:563089054119:web:a69a72a65658097268fe82',
    messagingSenderId: '563089054119',
    projectId: 'fabmaster-ad965',
    authDomain: 'fabmaster-ad965.firebaseapp.com',
    storageBucket: 'fabmaster-ad965.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEj1gLdXXw3Asm04p67YHQlLJca2LjUaA',
    appId: '1:563089054119:android:1f6c0630e49ad6cf68fe82',
    messagingSenderId: '563089054119',
    projectId: 'fabmaster-ad965',
    storageBucket: 'fabmaster-ad965.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvam7XqyqoKWjKn3zIOSVJUim02AE26M',
    appId: '1:563089054119:ios:bdc01f93d137e11b68fe82',
    messagingSenderId: '563089054119',
    projectId: 'fabmaster-ad965',
    storageBucket: 'fabmaster-ad965.appspot.com',
    iosBundleId: 'com.example.fabMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvam7XqyqoKWjKn3zIOSVJUim02AE26M',
    appId: '1:563089054119:ios:bdc01f93d137e11b68fe82',
    messagingSenderId: '563089054119',
    projectId: 'fabmaster-ad965',
    storageBucket: 'fabmaster-ad965.appspot.com',
    iosBundleId: 'com.example.fabMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLJpEQ1Lw2_ab1b_P7L49vCmNBsX9WqUo',
    appId: '1:563089054119:web:8f57f2755e23bdea68fe82',
    messagingSenderId: '563089054119',
    projectId: 'fabmaster-ad965',
    authDomain: 'fabmaster-ad965.firebaseapp.com',
    storageBucket: 'fabmaster-ad965.appspot.com',
  );
}
